version: '3.8'
services:
  freshrss:
    build:
      context: https://github.com/FreshRSS/FreshRSS.git#latest
      dockerfile: Docker/Dockerfile-Alpine
    restart: unless-stopped
    container_name: freshRss
    ports:
      - ${FRESHRSS_PORT}:80
    environment:
      - TZ=${TZ}             
      - CRON_MIN=${CRON_MIN}
      - BASE_URL=${BASE_URL}
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
      - ./config.php:/var/www/FreshRSS/data/config.php
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - rsshub
  rsshub:
    image: diygod/rsshub
    restart: unless-stopped
    container_name: rss_hub
    environment:
      - CACHE_TYPE=redis
      - NODE_ENV=production
      - REDIS_URL=redis://redis_db:6379
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    ports:                      
      - ${RSSHUB_PORT}:1200
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - redis_db
  redis_db:
    image: redis
    build: .
    container_name: redis_cache
    volumes:
        - redis_data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    container_name: full_feed_rss
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - rss-cache:/var/www/html/cache
    ports:                      
      - ${FULL_FEED_RSS_PORT}:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    container_name: watch_tower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - TZ=${TZ}
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE}
volumes:
  freshrss_data:
  freshrss_extensions:
  redis_data:
  rss-cache:
