version: '3.8'
services:
  proxy:
    image: nginx
    container_name: proxy_server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - freshRss
  freshRss:
    image: freshrss/freshrss
    restart: unless-stopped
    container_name: freshRss
    # ports:
    #   - 8080:80
    environment:
      - TZ=Asia/Kolkata             
      - CRON_MIN=1,31
      - BASE_URL=http://localhost/ # change to your domain base url
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
      - ./config.php:/var/www/FreshRSS/data/config.php
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    container_name: watch_tower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 0 * * 0
      - TZ="Asia/Kolkata"
      - WATCHTOWER_LABEL_ENABLE=true
volumes:
  freshrss_data:
  freshrss_extensions:
