version: '3.8'
services:
  freshRss:
    image: freshrss/freshrss
    restart: unless-stopped
    container_name: freshRss
    ports:
      - 80:80
    environment:
      - TZ=Asia/Kolkata             # Select your country code from https://www.php.net/timezones
      - CRON_MIN=1,31
      - BASE_URL=http://localhost/ # change to your domain base url
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
      - ./config.php:/var/www/FreshRSS/data/config.php
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    container_name: full_feed_rss
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - rss-cache:/var/www/html/cache
    # ports:                        #Comment out these two lines for local deployment
      # - "90:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    container_name: watch_tower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 0 * * 0
      - TZ="Asia/Kolkata"             # Select your country code from https://www.php.net/timezones
      - WATCHTOWER_LABEL_ENABLE=true
volumes:
  freshrss_data:
  freshrss_extensions:
